[package]
description = "A multi-protocol terminal emulator and serial console"
edition = "2021"
name = "rutty"
version = "0.4.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-io = "1.6"
futures = "0.3"
nix = "0.23"
ssh2 = "0.9"
structopt = "0.3"
zeroize = "1.5"

[dependencies.tokio]
features = ["rt", "io-std", "io-util", "net", "macros"]
version = "1.15"
