[package]
description = "A multi-protocol terminal emulator and serial console"
edition = "2021"
name = "rutty"
version = "0.5.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-io = "2.4"
async-recursion = "1.1"
futures = "0.3"
indicatif = "0.17"
ssh2 = "0.9"
structopt = "0.3"
zeroize = "1.8"

[dependencies.nix]
features = ["fs", "ioctl", "term", "user"]
version = "0.29"

[dependencies.tokio]
features = ["rt", "fs", "io-std", "io-util", "net", "macros"]
version = "1.41"
